on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test Web Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm test -- --coverage
      - name: Build Application
        run: npm run build
      - name: Upload Artifact for Deployment
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./build
  deploy:
    name: Deploy Web Application
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download Artifact for Deployment
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build